user:
    resource: "@UserBundle/Controller/"
    type:     annotation

page:
    resource: "@PageBundle/Controller/"
    type:     annotation

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation

item:
    resource: "@ItemBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
